### PR TITLE
114 action buttons more prominent

### LINKED ISSUE #117: Back button looks like straight text instead, should look like a button
- style like the next button

### PR DESCRIPTION
**Pull request by Sweta-Alla**
closes #117

### CODE REVIEW

**Comment by Sweta-Alla** [comment]
fixes #114

**Comment by berit** [comment]
thing that needs to be fixed:
- add exit button disabled style
- exit button turning white in some places??

**Comment by niharikasingh** [comment]
Plan for changing colors of buttons: 

1. Exit button in black - white/gray on hover 
1. Restart button in black - white/gray on hover (same as above)
1. Back button in red - darker red on hover 
1. Answer buttons in white - gray on hover

**Comment by Sweta-Alla** [comment]
Screen Shot 2020-09-22 at 8 00 15 PM
Screen Shot 2020-09-22 at 8 00 52 PM

**Review by niharikasingh — APPROVED** [review]

**Pull request merged**
